### ISSUE TITLE
Feature Request: Support environment variable for version

### ISSUE THREAD

**Issue by derekmurawsky** [linuxserver/docker-docker-compose#12]
## Expected Behavior

Set a DOCKER_COMPOSE_VERSION environment variable and have the run script use it. 
If the environment variable doesn't exist, have it default to latest. 

## Current Behavior

In order to change versions you have to edit the run script itself. 

## Thoughts

Keeping config in the environment is a normal and accepted pattern. Having version pinning is also a normal/desired feature from a CICD perspective. Having to edit the script to run docker-compose in a specific version seems like an anti-pattern. 

It think this change is as easy as changing

```sh
VERSION="latest" # can be set to a specific version tag from docker hub, such as "1.25.5", or "alpine"
IMAGE="linuxserver/docker-compose:$VERSION"
```
to
```sh
DOCKER_COMPOSE_VERSION:="latest" # can be set to a specific version tag from docker hub, such as "1.25.5", or "alpine"
IMAGE="linuxserver/docker-compose:$DOCKER_COMPOSE_VERSION"
```

I would be happy to put in a PR if this is something others would like. Perhaps a different Variable name to prevent confusion between the docker version and the container version?

**Comment by aptalca** [comment]
To clarify, it is not referring to docker compose version, it is referring to docker image tag, which you can find listed here: https://hub.docker.com/r/linuxserver/docker-compose/tags

Defaulting it to `latest` if unset is fine. Feel free to open a PR
