### ISSUE TITLE
Broken docker-compose link

### ISSUE THREAD

**Issue by frafra** [linuxserver/docker-docker-compose#34]
README uses https://github.com/docker-compose/docker-compose as URL instead of https://github.com/docker/compose. I was going to open a PR, but I read `<!---  If this is a fix for a typo (in code, documentation, or the README) please file an issue and let us sort it out. We do not need a PR  -->` :-)

**Comment by frafra** [comment]
Still relevant.

**Comment by nemchik** [comment]
Fixed in #35 #36 #37
